services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_service
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes:
  db-data: