definitions:
  github_com_WebChads_AccountService_internal_models_dtos.CreateAccountRequest:
    properties:
      birthdate:
        example: "1990-01-01"
        type: string
      firstname:
        example: Иван
        type: string
      gender:
        example: male
        type: string
      patronymic:
        example: Иванович
        type: string
      surname:
        example: Иванов
        type: string
    required:
    - birthdate
    - firstname
    - gender
    - surname
    type: object
  github_com_WebChads_AccountService_internal_models_dtos.GetAccountResponse:
    properties:
      age:
        example: 33
        type: integer
      birthdate:
        example: "1990-01-01T00:00:00Z"
        type: string
      firstname:
        example: Иван
        type: string
      gender:
        example: male
        type: string
      patronymic:
        example: Иванович
        type: string
      surname:
        example: Иванов
        type: string
      user_id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
    type: object
  github_com_WebChads_AccountService_internal_models_dtos.Response:
    properties:
      message: {}
      status:
        example: 200
        type: integer
    type: object
info:
  contact:
    email: support@example.com
    name: API Support
    url: https://example.com/support
  description: API for managing user accounts and authentication
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Account Service API
  version: "1.0"
paths:
  /api/v1/account/create-account:
    post:
      consumes:
      - application/json
      description: Creates a new user account with provided details
      parameters:
      - description: Account creation data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_WebChads_AccountService_internal_models_dtos.CreateAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_WebChads_AccountService_internal_models_dtos.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_WebChads_AccountService_internal_models_dtos.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_WebChads_AccountService_internal_models_dtos.Response'
      summary: Create new account
      tags:
      - Account
  /api/v1/account/get-account/{user_id}:
    get:
      consumes:
      - application/json
      description: Returns account information for specified user ID
      parameters:
      - description: User ID
        example: '"550e8400-e29b-41d4-a716-446655440000"'
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_WebChads_AccountService_internal_models_dtos.GetAccountResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_WebChads_AccountService_internal_models_dtos.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_WebChads_AccountService_internal_models_dtos.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_WebChads_AccountService_internal_models_dtos.Response'
      summary: Get user account by ID
      tags:
      - Account
schemes:
- http
swagger: "2.0"
